t

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -18,6 +18,14 @@ on:
       SKIP_DEVELOPER_MODE_CHECK:
         description: 'Skip Developer Mode Check'
         default: false
+      RELEASE_TYPE:
+        description: 'Release Type'
+        required: true
+        default: 'RELEASE'
+        validation:
+          pattern: '^(RELEASE|STAGING)$'
+          error-message: 'Valid values are RELEASE, STAGING'
+      
       
 
 jobs:
@@ -36,7 +44,7 @@ jobs:
         run: |
           yarn install
 
-      - name: Build Android release
+      - name: Setting Secrets
         run: |
           echo "" >> .env
           echo "JWT_SIGNATURE=${{ github.event.inputs.JWT_SIGNATURE }}" >> .env
@@ -45,8 +53,21 @@ jobs:
           echo "VERSION_NAME=${{ github.event.inputs.VERSION_NAME }}" >> .env
           echo "SKIP_DEVELOPER_MODE_CHECK=${{ github.event.inputs.SKIP_DEVELOPER_MODE_CHECK }}" >> .env
 
+          sed -i "s/{Your Deployment Key}/${{ secrets.CODE_PUSH_DEPLOYMENT_KEY }}/" "./android/app/src/main/res/values/strings.xml"
+
+          if [[ "${{ github.event.inputs.RELEASE_TYPE }}" == "RELEASE" ]]; then
+            sed -i "s/{Your app secret here}/${{ secrets.CODE_PUSH_DEPLOYMENT_KEY_PRODUCTION }}/" "./android/app/src/main/assets/appcenter-config.json"
+          elif [[ "${{ github.event.inputs.RELEASE_TYPE }}" == "STAGING" ]]; then
+            sed -i "s/{Your app secret here}/${{ secrets.CODE_PUSH_DEPLOYMENT_KEY_STAGING }}/" "./android/app/src/main/assets/appcenter-config.json"
+          else
+            echo "Invalid RELEASE_TYPE. Supported values are RELEASE, STAGING."
+            exit 1
+          fi
+
           sh ./setup/run.sh
 
+      - name: Build Android release
+        run: |
           cd android
           ./gradlew assembleRelease
 
